// app/layout.jsx
import "./globals.css";
import DashboardLayout from "./layout.client.jsx";

export const metadata = {
  title: "Shortlix AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
